INSERT INTO BOOKS (ID, NAME, PAGES) VALUES ('1','GOT', 567);
INSERT INTO BOOKS (ID, NAME, PAGES) VALUES ('2','HP', 100);
INSERT INTO BOOKS (ID, NAME, PAGES) VALUES ('3','JAVA', 200);
INSERT INTO BOOKS (ID, NAME, PAGES) VALUES ('4', 'DS', 300);
